use_frameworks!

install! 'cocoapods', :warn_for_unused_master_specs_repo => false

def proton_url
  'git@' + ENV["PROTON_GIT_URL"]
end

def protoncore_dependencies
  pod 'TrustKit', :git=> 'https://github.com/ProtonMail/TrustKit.git', :branch => 'master', :inhibit_warnings => true

  # we need to point to repo until the new version supporting Xcode 13 is released to cocoapods trunk
  pod 'AwaitKit', :git=> 'https://github.com/yannickl/AwaitKit.git', :branch => 'master', :inhibit_warnings => true
  
  pod 'OHHTTPStubs/Swift'
  pod 'TPInAppReceipt'
end

def all_protoncore_pods
  pod 'ProtonCore-AccountSwitcher', :path => '../'
  pod 'ProtonCore-APIClient/Alamofire', :path => '../'
  pod 'ProtonCore-Authentication-KeyGeneration/UsingCrypto+Alamofire', :path => '../'
  pod 'ProtonCore-Authentication/UsingCrypto+Alamofire', :path => '../'
  pod 'ProtonCore-Challenge', :path => '../'
  pod 'ProtonCore-Common/Alamofire', :path => '../'
  pod 'ProtonCore-CoreTranslation', :path => '../'
  pod 'ProtonCore-Crypto', :path => '../'
  pod 'ProtonCore-DataModel', :path => '../'
  pod 'ProtonCore-Doh', :path => '../'
  pod 'ProtonCore-Features/UsingCrypto+Alamofire', :path => '../'
  pod 'ProtonCore-ForceUpgrade/Alamofire', :path => '../'
  pod 'ProtonCore-Foundations', :path => '../'
  pod 'ProtonCore-GoSRP', :path => '../'
  pod 'ProtonCore-HumanVerification/Alamofire', :path => '../'
  pod 'ProtonCore-Keymaker/UsingCrypto', :path => '../'
  pod 'ProtonCore-KeyManager/UsingCrypto', :path => '../'
  pod 'ProtonCore-Log', :path => '../'
  pod 'ProtonCore-Login/UsingCrypto+Alamofire', :path => '../'
  pod 'ProtonCore-Networking/Alamofire', :path => '../'
  pod 'ProtonCore-ObfuscatedConstants', :path => '../'
  pod 'ProtonCore-OpenPGP', :path => '../'
  pod 'ProtonCore-Payments/UsingCrypto+Alamofire', :path => '../'
  pod 'ProtonCore-PaymentsUI/UsingCrypto+Alamofire', :path => '../'
  pod 'ProtonCore-Services/Alamofire', :path => '../'
  pod 'ProtonCore-Settings', :path => '../'
  pod 'ProtonCore-SRP', :path => '../'
  pod 'ProtonCore-UIFoundations', :path => '../'
  pod 'ProtonCore-Utilities', :path => '../'
  pod 'ProtonCore-VCard', :path => '../'
end

def all_protoncore_unit_tests
  pod 'ProtonCore-TestingToolkit/UnitTests/Core', :path => '../'
  
  pod 'ProtonCore-TestingToolkit/UnitTests/DataModel', :path => '../'
  pod 'ProtonCore-DataModel', :path => '../', :testspecs => ["Tests"]

  pod 'ProtonCore-TestingToolkit/UnitTests/Doh', :path => '../'
  pod 'ProtonCore-Doh', :path => '../', :testspecs => ["Tests"]

  pod 'ProtonCore-TestingToolkit/UnitTests/Networking/Alamofire', :path => '../'
  pod 'ProtonCore-Networking/Alamofire', :path => '../', :testspecs => ["Tests"]

  pod 'ProtonCore-TestingToolkit/UnitTests/HumanVerification/Alamofire', :path => '../'
  pod 'ProtonCore-TestingToolkit/UnitTests/Services/Alamofire', :path => '../'
  
  pod 'ProtonCore-TestingToolkit/UnitTests/Authentication/UsingCrypto+Alamofire', :path => '../'
  pod 'ProtonCore-Authentication/UsingCrypto+Alamofire', :path => '../', :testspecs => ["Tests"]

  pod 'ProtonCore-TestingToolkit/UnitTests/Authentication-KeyGeneration/UsingCrypto+Alamofire', :path => '../'
  pod 'ProtonCore-Authentication-KeyGeneration/UsingCrypto+Alamofire', :path => '../', :testspecs => ["Tests"]

  pod 'ProtonCore-TestingToolkit/UnitTests/Payments/UsingCrypto+Alamofire', :path => '../'
  pod 'ProtonCore-Payments/UsingCrypto+Alamofire', :path => '../', :testspecs => ["Tests"]
  pod 'ProtonCore-PaymentsUI/UsingCrypto+Alamofire', :path => '../', :testspecs => ["Tests"]

  pod 'ProtonCore-TestingToolkit/UnitTests/Login/UsingCrypto+Alamofire', :path => '../'
  pod 'ProtonCore-Login/UsingCrypto+Alamofire', :path => '../', :testspecs => ["Tests"]

  pod 'ProtonCore-AccountSwitcher', :path => '../', :testspecs => ["Tests"] 
  pod 'ProtonCore-APIClient/Alamofire', :path => '../', :testspecs => ["TestsUsingCrypto"]
  pod 'ProtonCore-Challenge', :path => '../', :testspecs => ["Tests"]
  pod 'ProtonCore-Common/Alamofire', :path => '../', :testspecs => ["Tests"]
  pod 'ProtonCore-Crypto', :path => '../', :testspecs => ["Tests"]
  pod 'ProtonCore-ForceUpgrade/Alamofire', :path => '../', :testspecs => ["Tests"]
  pod 'ProtonCore-Foundations', :path => '../', :testspecs => ["Tests"]
  pod 'ProtonCore-HumanVerification/Alamofire', :path => '../', :testspecs => ["Tests"]
  pod 'ProtonCore-Keymaker/UsingCrypto', :path => '../', :testspecs => ["Tests"]
  pod 'ProtonCore-KeyManager/UsingCrypto', :path => '../', :testspecs => ["Tests"]
  pod 'ProtonCore-Log', :path => '../', :testspecs => ["Tests"]
  pod 'ProtonCore-Settings', :path => '../', :testspecs => ["Tests"]
  pod 'ProtonCore-UIFoundations', :path => '../', :testspecs => ["Tests"]
  pod 'ProtonCore-Utilities', :path => '../', :testspecs => ["Tests"]
end

def shared_uitests_dependencies
  protoncore_dependencies
  pod 'pmtest', :git => 'git@gitlab.protontech.ch:apple/shared/pmtestautomation.git'
  pod 'ProtonCore-Doh', :path => '../'
  pod 'ProtonCore-TestingToolkit/TestData', :path => '../'
  pod 'ProtonCore-TestingToolkit/UITests/Core/Alamofire', :path => '../'
end

abstract_target 'iOS' do

  platform :ios, '11.0'

  target 'Example-iOS-ProtonCore-NoIAP' do
    protoncore_dependencies
    all_protoncore_pods
  end

  target 'Example-iOS-Mail-AppStoreIAP' do
    protoncore_dependencies
    all_protoncore_pods
  end

  target 'Example-iOS-Mail-LocalIAP' do
    protoncore_dependencies
    all_protoncore_pods
  end

  target 'Example-iOS-VPN-AppStoreIAP' do
    protoncore_dependencies
    all_protoncore_pods
  end

  target 'Example-iOS-VPN-LocalIAP' do
    protoncore_dependencies
    all_protoncore_pods
  end

  target 'Example-iOS-Drive-AppStoreIAP' do
    protoncore_dependencies
    all_protoncore_pods
  end

  target 'Example-iOS-Drive-LocalIAP' do
    protoncore_dependencies
    all_protoncore_pods
  end

  target 'Example-iOS-Calendar-AppStoreIAP' do
    protoncore_dependencies
    all_protoncore_pods
  end

  target 'Example-iOS-Calendar-LocalIAP' do
    protoncore_dependencies
    all_protoncore_pods
  end

  target 'Example-UnitTests' do
    protoncore_dependencies
    all_protoncore_unit_tests
  end

  target 'Example-AccountSwitcher-UITests' do
    shared_uitests_dependencies

    pod 'ProtonCore-TestingToolkit/UITests/AccountSwitcher', :path => '../'
  end

  target 'Example-Login-UITests' do
    shared_uitests_dependencies
    
    pod 'ProtonCore-TestingToolkit/UITests/Login', :path => '../'
    pod 'ProtonCore-TestingToolkit/UITests/PaymentsUI', :path => '../'
  end

  target 'Example-Payments-UITests' do
    shared_uitests_dependencies
    
    pod 'ProtonCore-TestingToolkit/UITests/Login', :path => '../'
    pod 'ProtonCore-TestingToolkit/UITests/PaymentsUI', :path => '../'
  end

end

def all_protoncore_macos_pods
#  pod 'ProtonCore-AccountSwitcher', :path => '../'
  pod 'ProtonCore-APIClient/Alamofire', :path => '../'
  pod 'ProtonCore-Authentication-KeyGeneration/UsingCrypto+Alamofire', :path => '../'
  pod 'ProtonCore-Authentication/UsingCrypto+Alamofire', :path => '../'
#  pod 'ProtonCore-Challenge', :path => '../'
  pod 'ProtonCore-Common/Alamofire', :path => '../'
  pod 'ProtonCore-CoreTranslation', :path => '../'
  pod 'ProtonCore-Crypto', :path => '../'
  pod 'ProtonCore-DataModel', :path => '../'
  pod 'ProtonCore-Doh', :path => '../'
#  pod 'ProtonCore-Features/UsingCrypto+Alamofire', :path => '../'
  pod 'ProtonCore-ForceUpgrade/Alamofire', :path => '../'
  pod 'ProtonCore-Foundations', :path => '../'
  pod 'ProtonCore-GoSRP', :path => '../'
  # pod 'ProtonCore-HumanVerification/Alamofire', :path => '../'
  pod 'ProtonCore-Keymaker/UsingCrypto', :path => '../'
  pod 'ProtonCore-KeyManager/UsingCrypto', :path => '../'
  pod 'ProtonCore-Log', :path => '../'
  # pod 'ProtonCore-Login/UsingCrypto+Alamofire', :path => '../'
#  pod 'ProtonCore-LoginUI/UsingCrypto+Alamofire', :path => '../'
  pod 'ProtonCore-Networking/Alamofire', :path => '../'
  pod 'ProtonCore-ObfuscatedConstants', :path => '../'
  pod 'ProtonCore-OpenPGP', :path => '../'
  pod 'ProtonCore-Payments/UsingCrypto+Alamofire', :path => '../'
#  pod 'ProtonCore-PaymentsUI/UsingCrypto+Alamofire', :path => '../'
  pod 'ProtonCore-Services/Alamofire', :path => '../'
#  pod 'ProtonCore-Settings', :path => '../'
  pod 'ProtonCore-SRP', :path => '../'
  pod 'ProtonCore-UIFoundations', :path => '../'
  pod 'ProtonCore-Utilities', :path => '../'
  pod 'ProtonCore-VCard', :path => '../'
end

abstract_target 'macOS' do
  platform :osx, '10.13'

  target 'Example-macOS' do
    protoncore_dependencies
    all_protoncore_macos_pods
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

