include:
  # Include non-i18n jobs only when I18N_SCHEDULES_FILTER is not set
  - local: 'ci/ci-jobs.yml'
    rules:
      - if: $I18N_SCHEDULES_FILTER || $SCHEDULE_REASON == 'commit-translations'
        when: never
      - when: always

  # i18n includes - always included
  - project: "translations/generator"
    ref: master
    file: "/jobs/sync-crowdin.gitlab-ci.yml"

  - project: "translations/generator"
    ref: master
    file: "/jobs/commit-locales.gitlab-ci.yml"

stages:
  - i18n
  - linting
  - summarise
  - offline_tests
  - deploy
  - trigger
  - online_tests
  - report
  - cleanup
  - github

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  GEM_HOME: "$CI_PROJECT_DIR/gem"
  GIT_DEPTH: 20
  GIT_STRATEGY: clone
  FF_ENABLE_JOB_CLEANUP: "true"

workflow:
  rules:
    - if: $I18N_SCHEDULES_FILTER
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "develop"
      variables:
        ATLAS_DEPLOY_ENV: "true"

    - if: $CI_OPEN_MERGE_REQUESTS
      when: never

    - if: $CI_PIPELINE_SOURCE == "push"
      when: never

    - if: $CI_COMMIT_BRANCH
      variables:
        TEST: "manual"

#
# --- Translation related tasks ---
#

i18n-crowdin-sync:
  stage: i18n
  needs: []
  variables:
    I18N_SYNC_CROWDIN_PROJECT: "apple-core"
  extends: .i18n-sync-crowdin-shared-apple

i18n-commit-locales:
  stage: i18n
  needs: []
  variables:
    I18N_COMMIT_CROWDIN_PROJECT: "apple-core"
  extends: .i18n-commit-locales-shared-apple
