
platform :ios, '11.0'
use_frameworks!

install! 'cocoapods', :warn_for_unused_master_specs_repo => false

def proton_url
  'git@' + ENV["PROTON_GIT_URL"]
end

def common_sample_pods
    # we need to point to repo until the new version supporting Xcode 13 is released to cocoapods trunk
    pod 'AwaitKit', :git=> 'https://github.com/yannickl/AwaitKit.git', :branch => 'master', :inhibit_warnings => true

    pod 'ProtonCore-Utilities', :path => '../../'
    pod 'ProtonCore-APIClient', :path => '../../'
    pod 'ProtonCore-Networking', :path => '../../'
    pod 'ProtonCore-DataModel', :path => '../../'
    pod 'ProtonCore-Services', :path => '../../'
    pod 'ProtonCore-Doh', :path => '../../'
    pod 'ProtonCore-OpenPGP', :path => '../../'

    pod 'ProtonCore-CoreTranslation', :path => '../../'
    pod 'ProtonCore-Challenge', :path => '../../'
    pod 'ProtonCore-HumanVerification', :path => '../../'
    pod 'ProtonCore-Log', :path => '../../'
    pod 'ProtonCore-Foundations', :path => '../../'
    pod 'ProtonCore-ForceUpgrade', :path => '../../'
    pod 'ProtonCore-SRP', :path => '../../'
    pod 'ProtonCore-UIFoundations', :path => '../../'

    pod 'ProtonCore-Authentication/UsingCryptoVPN', :path => '../../'
    pod 'ProtonCore-Authentication-KeyGeneration/UsingCryptoVPN', :path => '../../'
    pod 'ProtonCore-Login/UsingCryptoVPN', :path => '../../'
    pod 'ProtonCore-Payments/UsingCryptoVPN', :path => '../../'
    pod 'ProtonCore-PaymentsUI/UsingCryptoVPN', :path => '../../'
    pod 'ProtonCore-Crypto-VPN', :path => '../../'
    
    pod 'OHHTTPStubs/Swift'
    pod 'SwiftLint'
end

target 'SampleApp' do
  common_sample_pods
end

target 'SampleLocalMailApp' do
  common_sample_pods
end

target 'SampleAppUITests' do
   pod 'pmtest', :git => 'git@gitlab.protontech.ch:apple/shared/pmtestautomation.git', :branch => 'master'
   pod 'ProtonCore-Doh', :path => '../../'
   pod 'ProtonCore-Networking', :path => '../../'
#pod 'CryptoSwift', '1.4.1'  somehow 1.4.1 on pod server is missing ISO10126Padding. we can chagne this back later
   pod 'CryptoSwift', :git => 'https://github.com/krzyzanowskim/CryptoSwift.git', :tag => '1.4.1'
   pod 'SwiftOTP'
   pod 'ProtonCore-TestingToolkit/UITests/Login', :path => '../../'
   pod 'ProtonCore-TestingToolkit/UITests/PaymentsUI', :path => '../../'
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
   config.build_settings['ENABLE_BITCODE'] = 'NO'
  end
 end
end
