platform :ios, '11.0'
use_frameworks!

install! 'cocoapods', :warn_for_unused_master_specs_repo => false

target 'SampleApp' do
  use_frameworks!

  pod 'ProtonCore-Log', :path => '../../'
  pod 'ProtonCore-CoreTranslation', :path => '../../'
  pod 'ProtonCore-UIFoundations', :path => '../../'
  pod 'ProtonCore-AccountSwitcher', :path => '../../'
  pod 'ProtonCore-Utilities', :path => '../../'
  pod 'ProtonCore-Foundations', :path => '../../'

end

target 'SampleAppUITests' do
    pod 'pmtest', :git => 'git@gitlab.protontech.ch:apple/shared/pmtestautomation.git', :branch => 'master'
    pod 'ProtonCore-TestingToolkit/UITests/AccountSwitcher', :path => '../../'
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
   config.build_settings['ENABLE_BITCODE'] = 'NO'
  end
 end
end
