//
//  Created on 25.03.2025.
//
//  Copyright (c) 2025 Proton AG
//
//  ProtonVPN is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  ProtonVPN is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with ProtonVPN.  If not, see <https://www.gnu.org/licenses/>.

import Foundation
import ProtonCoreCrypto
import ProtonCoreObservability

public struct DecodeSignInQRCode {

    public init() {}

    public struct Response {
        public let version: Int
        public let userCode: String
        public let encryptionKey: Data?
        public let clientId: String
    }

    public enum DecodeError: Error {
        case qrCodeNotRecognized
    }

    enum Constants {
        static let encryptionKeyLengthInBytes: Int = 32
    }

    /// qrCode is generated by GenerateSignInQRCode use case
    /// format for qrCode should be `userCode:encryptionKey:client`
    public func invoke(qrCode: String) throws -> Response {

        let regex = #/^([^:]*):([^:]*):([^:]*):([^:]*)$/#

        guard let match = qrCode.wholeMatch(of: regex) else {
            ObservabilityEnv.report(.qrLoginDecodeQRCode(status: .wrongNumberOfQRCodeComponents))
            throw DecodeError.qrCodeNotRecognized
        }

        let (_, versionString, userCode, key, clientId) = match.output

        guard let version = Int(versionString), version == GenerateSignInQRCode.QRCodeVersion else {
            ObservabilityEnv.report(.qrLoginDecodeQRCode(status: .versionNotSupported))
            throw DecodeError.qrCodeNotRecognized
        }

        guard !userCode.isEmpty else {
            ObservabilityEnv.report(.qrLoginDecodeQRCode(status: .invalidUserCode))
            throw DecodeError.qrCodeNotRecognized
        }

        /// Note: the encryption key can be empty. Some clients don't need the passphrase so they don't send a key.
        var keyData: Data? = nil
        if !key.isEmpty {
            keyData = Base64.decode(base64: String(key))

            guard keyData?.count == Constants.encryptionKeyLengthInBytes else {
                ObservabilityEnv.report(.qrLoginDecodeQRCode(status: .invalidEncryptionKey))
                throw DecodeError.qrCodeNotRecognized
            }
        }

        ObservabilityEnv.report(.qrLoginDecodeQRCode(status: .success))
        return Response(
            version: version,
            userCode: String(userCode),
            encryptionKey: keyData,
            clientId: String(clientId))
    }
}
