//
//  Created on 25.03.2025.
//
//  Copyright (c) 2025 Proton AG
//
//  ProtonVPN is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  ProtonVPN is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with ProtonVPN.  If not, see <https://www.gnu.org/licenses/>.

import Foundation
import ProtonCoreCrypto

public struct DecodeSignInQRCode {

    public init() {}

    public struct Response {
        public let userCode: String
        public let encryptionKey: Data
        public let clientId: String
    }

    public enum DecodeError: Error {
        case qrCodeNotRecognized
    }

    enum Constants {
        static let encryptionKeyLengthInBytes: Int = 32
    }

    /// qrCode is generated by GenerateSignInQRCode use case
    /// format for qrCode should be `userCode:encryptionKey:client`
    public func invoke(qrCode: String) throws -> Response {
        let components = qrCode.split(separator: ":")

        guard components.count == 3 else {
            throw DecodeError.qrCodeNotRecognized
        }

        let userCode = String(components[0])
        let key = String(components[1])
        let clientId = String(components[2])

        guard userCode != "" else {
            throw DecodeError.qrCodeNotRecognized
        }

        let keyData = Base64.decode(base64: key)

        guard keyData.count == Constants.encryptionKeyLengthInBytes else {
            throw DecodeError.qrCodeNotRecognized
        }

        return Response(userCode: userCode,
                        encryptionKey: Base64.decode(base64: key),
                        clientId: clientId)
    }
}
