source 'https://cdn.cocoapods.org/'

install! 'cocoapods', :warn_for_unused_master_specs_repo => false

def common_example_pods
  platform :ios, '11.0'
  use_frameworks!

  pod 'ProtonCore-Utilities', :path => '../../'
  pod 'ProtonCore-Crypto', :path => '../../'
  pod 'ProtonCore-OpenPGP', :path => '../../'
  pod 'ProtonCore-DataModel', :path => '../../'
  pod 'ProtonCore-Doh', :path => '../../'

  pod 'ProtonCore-HumanVerification', :path => '../../'
  pod 'ProtonCore-Log', :path => '../../'
  pod 'ProtonCore-Foundations', :path => '../../'
  pod 'ProtonCore-Authentication', :path => '../../'
  pod 'ProtonCore-SRP', :path => '../../'
  pod 'ProtonCore-UIFoundations', :path => '../../'
  pod 'ProtonCore-Payments', :path => '../../'
  pod 'ProtonCore-PaymentsUI', :path => '../../'
  pod 'ProtonCore-CoreTranslation', :path => '../../'
  pod 'ProtonCore-Challenge', :path => '../../'
  pod 'ProtonCore-Networking', :path => '../../'
  pod 'ProtonCore-APIClient', :path => '../../'
  pod 'ProtonCore-Services', :path => '../../'
  pod 'ProtonCore-Common', :path => '../../'
  
  pod 'SwiftLint'
end

target 'ExampleMailApp' do
  common_example_pods
end

target 'ExampleLocalMailApp' do
  common_example_pods
end

target 'ExampleVpnApp' do
  common_example_pods
end

target 'ExampleLocalVpnApp' do
  common_example_pods
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
   config.build_settings['ENABLE_BITCODE'] = 'NO'
  end
 end
end
