source 'https://cdn.cocoapods.org/'

install! 'cocoapods', :warn_for_unused_master_specs_repo => false

def common_pods
  platform :ios, '11.0'
  use_frameworks!

  # we need to point to repo until the new version supporting Xcode 13 is released to cocoapods trunk
  pod 'AwaitKit', :git=> 'https://github.com/yannickl/AwaitKit.git', :branch => 'master', :inhibit_warnings => true

  pod 'TPInAppReceipt'

  pod 'ProtonCore-Utilities', :path => '../../'
  pod 'ProtonCore-OpenPGP', :path => '../../'
  pod 'ProtonCore-DataModel', :path => '../../'
  pod 'ProtonCore-Doh', :path => '../../'

  pod 'ProtonCore-HumanVerification', :path => '../../'
  pod 'ProtonCore-Log', :path => '../../'
  pod 'ProtonCore-Foundations', :path => '../../'
  pod 'ProtonCore-SRP', :path => '../../'
  pod 'ProtonCore-UIFoundations', :path => '../../'
  pod 'ProtonCore-CoreTranslation', :path => '../../'
  pod 'ProtonCore-Challenge', :path => '../../'
  pod 'ProtonCore-Networking', :path => '../../'
  pod 'ProtonCore-APIClient', :path => '../../'
  pod 'ProtonCore-Services', :path => '../../'
  pod 'ProtonCore-Common', :path => '../../'

  pod 'ProtonCore-Authentication/UsingCryptoVPN', :path => '../../'
  pod 'ProtonCore-Payments/UsingCryptoVPN', :path => '../../'
  pod 'ProtonCore-PaymentsUI/UsingCryptoVPN', :path => '../../'
  pod 'ProtonCore-Crypto-VPN', :path => '../../'
  
  pod 'SwiftLint'
end

target 'Payments-Mail-AppStoreIAP' do
  common_pods
end

target 'Payments-Mail-LocalIAPConfiguration' do
  common_pods
end

target 'Payments-VPN-AppStoreIAP' do
  common_pods
end

target 'Payments-VPN-LocalIAPConfiguration' do
  common_pods
end

target 'Payments-Drive-AppStoreIAP' do
  common_pods
end

target 'Payments-Drive-LocalIAPConfiguration' do
  common_pods
end

target 'Payments-Calendar-AppStoreIAP' do
  common_pods
end

target 'Payments-Calendar-LocalIAPConfiguration' do
  common_pods
end

target 'Payments-UITests' do
  platform :ios, '11.0'
  use_frameworks!

  pod 'pmtest', :git => 'git@gitlab.protontech.ch:apple/shared/pmtestautomation.git', :branch => 'master'

  # we need to point to repo until the new version supporting Xcode 13 is released to cocoapods trunk
  pod 'AwaitKit', :git=> 'https://github.com/yannickl/AwaitKit.git', :branch => 'master', :inhibit_warnings => true

  pod 'ProtonCore-Crypto-VPN', :path => '../../'
  pod 'ProtonCore-Doh', :path => '../../'
  pod 'ProtonCore-Networking', :path => '../../'
  pod 'ProtonCore-Payments/UsingCryptoVPN', :path => '../../'
  pod 'ProtonCore-Services', :path => '../../'
  pod 'ProtonCore-TestingToolkit/UITests/Core/UsingCryptoVPN', :path => '../../'
  pod 'ProtonCore-TestingToolkit/UITests/Login', :path => '../../'
  pod 'ProtonCore-TestingToolkit/UITests/PaymentsUI', :path => '../../'
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
   config.build_settings['ENABLE_BITCODE'] = 'NO'
  end
 end
end
