use_frameworks!

platform :ios, '11.0'

# install! 'cocoapods', :warn_for_unused_master_specs_repo => false

target 'PMFeatures_Example' do

  pod 'ProtonCore-APIClient', :path => '../../'
  pod 'ProtonCore-Authentication', :path => '../../'
  pod 'ProtonCore-Authentication-KeyGeneration', :path => '../../'
  pod 'ProtonCore-Common', :path => '../../'
  pod 'ProtonCore-CoreTranslation', :path => '../../'
  pod 'ProtonCore-Crypto', :path => '../../'
  pod 'ProtonCore-DataModel', :path => '../../'
  pod 'ProtonCore-Doh', :path => '../../'
  pod 'ProtonCore-Log', :path => '../../'
  pod 'ProtonCore-Features', :path => '../../'
  pod 'ProtonCore-Foundations', :path => '../../'
  pod 'ProtonCore-KeyManager', :path => '../../'
  pod 'ProtonCore-Networking/Alamofire', :path => '../../'
  pod 'ProtonCore-OpenPGP', :path => '../../'
  pod 'ProtonCore-Services', :path => '../../'
  pod 'ProtonCore-SRP', :path => '../../'
  pod 'ProtonCore-Utilities', :path => '../../'
  pod 'ProtonCore-UIFoundations', :path => '../../'

  pod 'TrustKit', :git=> 'https://github.com/ProtonMail/TrustKit.git', :branch => 'master'

end


post_install do | installer |
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
