# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

def no_test_podspecs
  ""
end

def default_test_podspecs
  ",ProtonCore-ObfuscatedConstants.podspec,ProtonCore-TestingToolkit.podspec,fastlane/UsedOnlyForLintingAndNotForTheActualWork/TrustKit.podspec"
end

def lint_spec(name, platforms, test_podspecs, *additional_podspecs)
  # ProtonCore-TestingToolkit.podspec is added as implicit dependency to everything, otherwise the linting complains that it cannot resolve test_spec dependencies
  dependencies = sh("ruby", "../scripts/identify_local_podspecs.rb", "../ProtonCore-#{name}.podspec").lines.last.strip
                    .gsub("}",",#{additional_podspecs.map { |e| "ProtonCore-" + e + ".podspec"  }.join(',')}#{test_podspecs}}")
                    .gsub(",,",",") 
                    .gsub("{,","{")
                    .gsub(",}","}")
  pod_lib_lint(
    podspec: "ProtonCore-#{name}.podspec",
    allow_warnings: true,
    skip_tests: true,
    platforms: platforms,
    include_podspecs: dependencies,
    no_subspecs: true
  )
end

def lint_subspec(name, subspec, platforms, test_podspecs, *additional_podspecs)
  # ProtonCore-TestingToolkit.podspec is added as implicit dependency to everything, otherwise the linting complains that it cannot resolve test_spec dependencies
  dependencies = sh("ruby", "../scripts/identify_local_podspecs.rb", "../ProtonCore-#{name}.podspec", subspec).lines.last.strip
                    .gsub("}",",#{additional_podspecs.map { |e| "ProtonCore-" + e + ".podspec"  }.join(',')}#{test_podspecs}}")
                    .gsub("{,","{") 
                    .gsub(",,",",")
                    .gsub(",}","}")
  pod_lib_lint(
    podspec: "ProtonCore-#{name}.podspec",
    allow_warnings: true,
    skip_tests: true,
    platforms: platforms,
    subspec: subspec,
    include_podspecs: dependencies
  )
end

def derived_data_path
  "/Users/administrator/ProtonCore/UnitTests/" + ENV['CI_PIPELINE_IID'] + "/DerivedData/"
end

platform :ios do

  lane :lint_AccountSwitcher do
    lint_spec("AccountSwitcher", "ios", no_test_podspecs)
  end 

  lane :lint_APIClient_full do
    lint_subspec("APIClient", "Alamofire", "ios,macos", default_test_podspecs, "Crypto", "Crypto-VPN", "Authentication")
    lint_subspec("APIClient", "AFNetworking", "ios,macos", default_test_podspecs, "Crypto", "Crypto-VPN", "Authentication")
  end

  lane :lint_APIClient_lite do
    lint_subspec("APIClient", "Alamofire", "ios", default_test_podspecs, "Crypto", "Crypto-VPN", "Authentication")
  end

  lane :lint_Authentication_full do
    lint_subspec("Authentication", "UsingCrypto+Alamofire", "ios,macos", default_test_podspecs)
    lint_subspec("Authentication", "UsingCryptoVPN+Alamofire", "ios,macos", default_test_podspecs)
    lint_subspec("Authentication", "UsingCrypto+AFNetworking", "ios,macos", default_test_podspecs)
    lint_subspec("Authentication", "UsingCryptoVPN+AFNetworking", "ios,macos", default_test_podspecs)
  end

  lane :lint_Authentication_lite do
    lint_subspec("Authentication", "UsingCrypto+Alamofire", "ios", default_test_podspecs)
  end

  lane :lint_Authentication_KeyGeneration_full do
    lint_subspec("Authentication-KeyGeneration", "UsingCrypto+Alamofire", "ios,macos", default_test_podspecs)
    lint_subspec("Authentication-KeyGeneration", "UsingCryptoVPN+Alamofire", "ios,macos", default_test_podspecs)
    lint_subspec("Authentication-KeyGeneration", "UsingCrypto+AFNetworking", "ios,macos", default_test_podspecs)
    lint_subspec("Authentication-KeyGeneration", "UsingCryptoVPN+AFNetworking", "ios,macos", default_test_podspecs)
  end

  lane :lint_Authentication_KeyGeneration_lite do
    lint_subspec("Authentication-KeyGeneration", "UsingCrypto+Alamofire", "ios", default_test_podspecs)
  end

  lane :lint_Challenge do
    lint_spec("Challenge", "ios", no_test_podspecs)
  end

  lane :lint_Common_full do
    lint_subspec("Common", "Alamofire", "ios,macos", no_test_podspecs)
    lint_subspec("Common", "AFNetworking", "ios,macos", no_test_podspecs)
  end

  lane :lint_Common_lite do
    lint_subspec("Common", "Alamofire", "ios", no_test_podspecs)
  end

  lane :lint_CoreTranslation_full do
    lint_spec("CoreTranslation", "ios,macos", no_test_podspecs)
  end

  lane :lint_CoreTranslation_lite do
    lint_spec("CoreTranslation", "ios", no_test_podspecs)
  end

  lane :lint_Crypto_full do
    lint_spec("Crypto", "ios,macos", no_test_podspecs)
  end

  lane :lint_Crypto_lite do
    lint_spec("Crypto", "ios", no_test_podspecs)
  end

  lane :lint_Crypto_VPN_full do
    lint_spec("Crypto-VPN", "ios,macos", no_test_podspecs)
  end

  lane :lint_Crypto_VPN_lite do
    lint_spec("Crypto-VPN", "ios", no_test_podspecs)
  end

  lane :lint_DataModel_full do
    lint_spec("DataModel", "ios,macos", default_test_podspecs)
  end

  lane :lint_DataModel_lite do
    lint_spec("DataModel", "ios", default_test_podspecs)
  end

  lane :lint_Doh_full do
    lint_spec("Doh", "ios,macos", default_test_podspecs)
  end

  lane :lint_Doh_lite do
    lint_spec("Doh", "ios", default_test_podspecs)
  end

  lane :lint_Features_full do
    lint_subspec("Features", "UsingCrypto+Alamofire", "ios,macos", no_test_podspecs)
    lint_subspec("Features", "UsingCryptoVPN+Alamofire", "ios,macos", no_test_podspecs)
    lint_subspec("Features", "UsingCrypto+AFNetworking", "ios,macos", no_test_podspecs)
    lint_subspec("Features", "UsingCryptoVPN+AFNetworking", "ios,macos", no_test_podspecs)
  end

  lane :lint_Features_lite do
    lint_subspec("Features", "UsingCrypto+Alamofire", "ios", no_test_podspecs)
  end

  lane :lint_ForceUpgrade_full do
    lint_subspec("ForceUpgrade", "Alamofire", "ios,macos", no_test_podspecs)
    lint_subspec("ForceUpgrade", "AFNetworking", "ios,macos", no_test_podspecs)
  end

  lane :lint_ForceUpgrade_lite do
    lint_subspec("ForceUpgrade", "Alamofire", "ios", no_test_podspecs)
  end

  lane :lint_Foundations_full do
    lint_spec("Foundations", "ios,macos", no_test_podspecs)
  end

  lane :lint_Foundations_lite do
    lint_spec("Foundations", "ios", no_test_podspecs)
  end

  lane :lint_GoSRP_full do
    lint_spec("GoSRP", "ios,macos", no_test_podspecs)
  end

  lane :lint_GoSRP_lite do
    lint_spec("GoSRP", "ios", no_test_podspecs)
  end

  lane :lint_HumanVerification_full do
    lint_subspec("HumanVerification", "Alamofire", "ios,macos", default_test_podspecs)
    lint_subspec("HumanVerification", "AFNetworking", "ios,macos", default_test_podspecs)
  end

  lane :lint_HumanVerification_lite do
    lint_subspec("HumanVerification", "Alamofire", "ios", default_test_podspecs)
  end

  lane :lint_Keymaker_full do
    lint_subspec("Keymaker", "UsingCrypto", "ios,macos", no_test_podspecs)
    lint_subspec("Keymaker", "UsingCryptoVPN", "ios,macos", no_test_podspecs)
  end

  lane :lint_Keymaker_lite do
    lint_subspec("Keymaker", "UsingCrypto", "ios", no_test_podspecs)
  end

  lane :lint_KeyManager_full do
    lint_subspec("KeyManager", "UsingCrypto", "ios,macos", no_test_podspecs)
    lint_subspec("KeyManager", "UsingCryptoVPN", "ios,macos", no_test_podspecs)
  end

  lane :lint_KeyManager_lite do
    lint_subspec("KeyManager", "UsingCryptoVPN", "ios", no_test_podspecs)
  end

  lane :lint_Log_full do
    lint_spec("Log", "ios,macos", no_test_podspecs)
  end

  lane :lint_Log_lite do
    lint_spec("Log", "ios", no_test_podspecs)
  end

  lane :lint_Login_full do
    lint_subspec("Login", "UsingCrypto+Alamofire", "ios,macos", default_test_podspecs)
    lint_subspec("Login", "UsingCryptoVPN+Alamofire", "ios,macos", default_test_podspecs)
    lint_subspec("Login", "UsingCrypto+AFNetworking", "ios,macos", default_test_podspecs)
    lint_subspec("Login", "UsingCryptoVPN+AFNetworking", "ios,macos", default_test_podspecs)
  end

  lane :lint_Login_lite do
    lint_subspec("Login", "UsingCrypto+Alamofire", "ios", default_test_podspecs)
  end

  lane :lint_LoginUI_full do
    lint_subspec("LoginUI", "UsingCrypto+Alamofire", "ios", default_test_podspecs)
    lint_subspec("LoginUI", "UsingCryptoVPN+Alamofire", "ios", default_test_podspecs)
    lint_subspec("LoginUI", "UsingCrypto+AFNetworking", "ios", default_test_podspecs)
    lint_subspec("LoginUI", "UsingCryptoVPN+AFNetworking", "ios", default_test_podspecs)
  end

  lane :lint_LoginUI_lite do
    lint_subspec("LoginUI", "UsingCrypto+Alamofire", "ios", default_test_podspecs)
  end

  lane :lint_Networking_full do
    lint_subspec("Networking", "AFNetworking", "ios,macos", default_test_podspecs, "Utilities", "Doh", "Services", "APIClient", "Log", "DataModel")
    lint_subspec("Networking", "Alamofire", "ios,macos", default_test_podspecs, "Utilities", "Doh", "Services", "APIClient", "Log", "DataModel")
  end

  lane :lint_Networking_lite do
    lint_subspec("Networking", "Alamofire", "ios", default_test_podspecs, "Utilities", "Doh", "Services", "APIClient", "Log", "DataModel")
  end

  lane :lint_ObfuscatedConstants_full do
    lint_spec("ObfuscatedConstants", "ios,macos", no_test_podspecs)
  end

  lane :lint_ObfuscatedConstants_lite do
    lint_spec("ObfuscatedConstants", "macos", no_test_podspecs)
  end

  lane :lint_OpenPGP_full do
    lint_spec("OpenPGP", "ios,macos", no_test_podspecs)
  end

  lane :lint_OpenPGP_lite do
    lint_spec("OpenPGP", "ios", no_test_podspecs)
  end

  lane :lint_Payments_full do
    lint_subspec("Payments", "UsingCrypto+Alamofire", "ios,macos", default_test_podspecs)
    lint_subspec("Payments", "UsingCryptoVPN+Alamofire", "ios,macos", default_test_podspecs)
    lint_subspec("Payments", "UsingCrypto+AFNetworking", "ios,macos", default_test_podspecs)
    lint_subspec("Payments", "UsingCryptoVPN+AFNetworking", "ios,macos", default_test_podspecs)
  end

  lane :lint_Payments_lite do
    lint_subspec("Payments", "UsingCrypto+Alamofire", "ios", default_test_podspecs)
  end

  lane :lint_PaymentsUI_full do
    lint_subspec("PaymentsUI", "UsingCrypto+Alamofire", "ios", default_test_podspecs)
    lint_subspec("PaymentsUI", "UsingCryptoVPN+Alamofire", "ios", default_test_podspecs)
    lint_subspec("PaymentsUI", "UsingCrypto+AFNetworking", "ios", default_test_podspecs)
    lint_subspec("PaymentsUI", "UsingCryptoVPN+AFNetworking", "ios", default_test_podspecs)
  end

  lane :lint_PaymentsUI_lite do
    lint_subspec("PaymentsUI", "UsingCrypto+Alamofire", "ios", default_test_podspecs)
  end

  lane :lint_Services_full do
    lint_subspec("Services", "Alamofire", "ios,macos", no_test_podspecs)
    lint_subspec("Services", "AFNetworking", "ios,macos", no_test_podspecs)
  end

  lane :lint_Services_lite do
    lint_subspec("Services", "Alamofire", "ios", no_test_podspecs)
  end

  lane :lint_Settings do
    lint_spec("Settings", "ios", no_test_podspecs)
  end

  lane :lint_SRP_full do
    lint_spec("SRP", "ios,macos", no_test_podspecs)
  end

  lane :lint_SRP_lite do
    lint_spec("SRP", "ios", no_test_podspecs)
  end

  lane :lint_UIFoundations_full do
    lint_spec("UIFoundations", "ios,macos", no_test_podspecs)
  end

  lane :lint_UIFoundations_lite do
    lint_spec("UIFoundations", "ios", no_test_podspecs)
  end

  lane :lint_Utilities_full do
    lint_spec("Utilities", "ios,macos", no_test_podspecs)
  end

  lane :lint_Utilities_lite do
    lint_spec("Utilities", "ios", no_test_podspecs)
  end

  lane :lint_VCard_full do
    lint_spec("VCard", "ios,macos", no_test_podspecs)
  end

  lane :lint_VCard_lite do
    lint_spec("VCard", "ios", no_test_podspecs)
  end

  lane :lint_subspecs_full_1 do
    bundle_install(gemfile: "fastlane/Gemfile")
    lint_AccountSwitcher
    lint_APIClient_full
    lint_Authentication_full
  end

  lane :lint_subspecs_full_2 do
    bundle_install(gemfile: "fastlane/Gemfile")
    lint_Authentication_KeyGeneration_full
    lint_Challenge
    lint_Common_full
    lint_CoreTranslation_full
    lint_Crypto_full
    lint_Crypto_VPN_full
  end 

  lane :lint_subspecs_full_3 do
    bundle_install(gemfile: "fastlane/Gemfile")
    lint_DataModel_full
    lint_Doh_full
    lint_Features_full
    lint_ForceUpgrade_full
    lint_Foundations_full
    lint_GoSRP_full
    lint_HumanVerification_full
    lint_Keymaker_full
    lint_ObfuscatedConstants_full
    lint_LoginUI_full
  end

  lane :lint_subspecs_full_4 do
    bundle_install(gemfile: "fastlane/Gemfile")
    lint_Log_full
    lint_KeyManager_full
    lint_Login_full
    lint_Networking_full
    lint_OpenPGP_full
    lint_Payments_full
  end

  lane :lint_subspecs_full_5 do
    bundle_install(gemfile: "fastlane/Gemfile")
    lint_PaymentsUI_full
    lint_Services_full
    lint_Settings
    lint_SRP_full
    lint_UIFoundations_full
    lint_Utilities_full
    lint_VCard_full
  end

  lane :lint_all_subspecs_full do
    lint_subspecs_full_1
    lint_subspecs_full_2
    lint_subspecs_full_3
    lint_subspecs_full_4
    lint_subspecs_full_5
  end

  lane :lint_subspecs_lite_1 do
    bundle_install(gemfile: "fastlane/Gemfile")
    lint_AccountSwitcher
    lint_APIClient_lite
    lint_Authentication_lite
    lint_Authentication_KeyGeneration_lite
    lint_Challenge
  end

  lane :lint_subspecs_lite_2 do
    bundle_install(gemfile: "fastlane/Gemfile")
    lint_Common_lite
    lint_CoreTranslation_lite
    lint_Crypto_lite
    lint_Crypto_VPN_lite
    lint_DataModel_lite
    lint_Doh_lite
    lint_Features_lite
  end 

  lane :lint_subspecs_lite_3 do
    bundle_install(gemfile: "fastlane/Gemfile")
    lint_ForceUpgrade_lite
    lint_Foundations_lite
    lint_GoSRP_lite
    lint_HumanVerification_lite
    lint_Keymaker_lite
    lint_Log_lite
    lint_KeyManager_lite
    lint_ObfuscatedConstants_lite
    lint_LoginUI_lite
  end

  lane :lint_subspecs_lite_4 do
    bundle_install(gemfile: "fastlane/Gemfile")
    lint_Login_lite
    lint_Networking_lite
    lint_OpenPGP_lite
    lint_Payments_lite
    lint_Services_lite
  end

  lane :lint_subspecs_lite_5 do
    bundle_install(gemfile: "fastlane/Gemfile")
    lint_PaymentsUI_lite
    lint_Settings
    lint_SRP_lite
    lint_UIFoundations_lite
    lint_Utilities_lite
    lint_VCard_lite
  end

  lane :lint_all_subspecs_lite do
    lint_subspecs_lite_1
    lint_subspecs_lite_2
    lint_subspecs_lite_3
    lint_subspecs_lite_4
    lint_subspecs_lite_5
  end

  lane :run_tests_locally do
    sh("bash", "../scripts/generate_obfuscated_constants.sh", "--only-tests")
    run_tests(workspace: "example-app/ExampleApp.xcworkspace", scheme: "Example-UnitTests", build_for_testing: true)
    run_tests(workspace: "example-app/ExampleApp.xcworkspace", scheme: "Example-UnitTests", clean: false, skip_build: true)
  end

  lane :prepare_for_unit_tests do
    sh("echo", derived_data_path)
    sh("mkdir", "-p", derived_data_path)
    sh("bash", "../scripts/generate_obfuscated_constants.sh", "--only-tests")
    bundle_install(gemfile: "fastlane/Gemfile")
  end

  lane :run_unit_tests do
    build_app(
      workspace: "example-app/ExampleApp.xcworkspace",
      scheme: "Example-macOS-Mail-AppStoreIAP",
      derived_data_path: derived_data_path,
      clean: true,
      skip_archive: true,
      skip_codesigning: true
    )
    run_tests(
      workspace: "example-app/ExampleApp.xcworkspace",
      scheme: "Example-UnitTests",
      derived_data_path: derived_data_path,
      build_for_testing: true,
      code_coverage: true,
      result_bundle: true
    )
    run_tests(
      workspace: "example-app/ExampleApp.xcworkspace",
      scheme: "Example-UnitTests",
      clean: false,
      skip_build: true,
      derived_data_path: derived_data_path,
      code_coverage: true
    )
  end

  lane :cleanup_after_unit_tests do
    clear_derived_data(
      derived_data_path: derived_data_path
    )
    sh("rm", "-rf", derived_data_path)
  end

end
