platform :ios, '11.0'
use_frameworks!

install! 'cocoapods', :warn_for_unused_master_specs_repo => false

def proton_url
  'git@' + ENV["PROTON_GIT_URL"]
end

target 'CoreExample' do
  pod 'TrustKit', :git=> 'https://github.com/ProtonMail/TrustKit.git', :branch => 'master', :inhibit_warnings => true

  pod 'ProtonCore-AccountSwitcher', :path => '../../'
  pod 'ProtonCore-APIClient', :path => '../../'
  pod 'ProtonCore-Authentication', :path => '../../'
  pod 'ProtonCore-Authentication-KeyGeneration', :path => '../../'
  pod 'ProtonCore-Challenge', :path => '../../'
  pod 'ProtonCore-Common', :path => '../../'
  pod 'ProtonCore-CoreTranslation', :path => '../../'
  pod 'ProtonCore-Crypto', :path => '../../'
  pod 'ProtonCore-DataModel', :path => '../../'
  pod 'ProtonCore-Doh', :path => '../../'
  pod 'ProtonCore-ForceUpgrade', :path => '../../'
  pod 'ProtonCore-Foundations', :path => '../../'
  pod 'ProtonCore-GoSRP', :path => '../../'
  pod 'ProtonCore-HumanVerification', :path => '../../'
  pod 'ProtonCore-Keymaker', :path => '../../'
  pod 'ProtonCore-KeyManager', :path => '../../'
  pod 'ProtonCore-Log', :path => '../../'
  pod 'ProtonCore-Login', :path => '../../'
  pod 'ProtonCore-Networking/Alamofire', :path => '../../'
  pod 'ProtonCore-OpenPGP', :path => '../../'
  pod 'ProtonCore-Payments', :path => '../../'
  pod 'ProtonCore-PaymentsUI', :path => '../../'
  pod 'ProtonCore-SRP', :path => '../../'
  pod 'ProtonCore-Services', :path => '../../'
  pod 'ProtonCore-UIFoundations', :path => '../../'
  pod 'ProtonCore-Utilities', :path => '../../'
end

target 'CoreExample-UnitTests' do
  pod 'TrustKit', :git=> 'https://github.com/ProtonMail/TrustKit.git', :branch => 'master', :inhibit_warnings => true

  pod 'ProtonCore-AccountSwitcher', :path => '../../', :testspecs => ["Tests"]
  pod 'ProtonCore-APIClient', :path => '../../', :testspecs => ["Tests"]
  pod 'ProtonCore-Authentication', :path => '../../', :testspecs => ["Tests"]
  pod 'ProtonCore-Authentication-KeyGeneration', :path => '../../', :testspecs => ["Tests"]
  pod 'ProtonCore-Challenge', :path => '../../', :testspecs => ["Tests"]
  pod 'ProtonCore-Common', :path => '../../', :testspecs => ["Tests"]
  pod 'ProtonCore-DataModel', :path => '../../', :testspecs => ["Tests"]
  pod 'ProtonCore-Doh', :path => '../../', :testspecs => ["Tests"]
  pod 'ProtonCore-ForceUpgrade', :path => '../../', :testspecs => ["Tests"]
  pod 'ProtonCore-Foundations', :path => '../../', :testspecs => ["Tests"]
  pod 'ProtonCore-HumanVerification', :path => '../../', :testspecs => ["Tests"]
  pod 'ProtonCore-Keymaker', :path => '../../', :testspecs => ["Tests"]
  pod 'ProtonCore-KeyManager', :path => '../../', :testspecs => ["Tests"]
  pod 'ProtonCore-Log', :path => '../../', :testspecs => ["Tests"]
  pod 'ProtonCore-Login', :path => '../../', :testspecs => ["Tests"]
  pod 'ProtonCore-Networking/Alamofire', :path => '../../'  #, :testspecs => ["Tests"]
  pod 'ProtonCore-Payments', :path => '../../', :testspecs => ["Tests"]
  pod 'ProtonCore-PaymentsUI', :path => '../../', :testspecs => ["Tests"]
  pod 'ProtonCore-UIFoundations', :path => '../../', :testspecs => ["Tests"]
  pod 'ProtonCore-Utilities', :path => '../../', :testspecs => ["Tests"]
  pod 'ProtonCore-Crypto', :path => '../../', :testspecs => ["Tests"]

  pod 'ProtonCore-TestingToolkit/UnitTests/Core', :path => '../../'
  pod 'ProtonCore-TestingToolkit/UnitTests/Doh', :path => '../../'
  pod 'ProtonCore-TestingToolkit/UnitTests/HumanVerification', :path => '../../'
  pod 'ProtonCore-TestingToolkit/UnitTests/Login', :path => '../../'
  pod 'ProtonCore-TestingToolkit/UnitTests/Services', :path => '../../'
  pod 'ProtonCore-TestingToolkit/UnitTests/Payments', :path => '../../'
end

target 'CoreExample-UITests' do

  pod 'pmtest', :git => 'git@gitlab.protontech.ch:apple/shared/pmtestautomation.git', :commit => '0878ae03'

  pod 'ProtonCore-TestingToolkit/UITests/HumanVerification', :path => '../../'
  pod 'ProtonCore-TestingToolkit/UITests/Login', :path => '../../'
  pod 'ProtonCore-TestingToolkit/UITests/AccountSwitcher', :path => '../../'
  pod 'ProtonCore-TestingToolkit/UITests/PaymentsUI', :path => '../../'
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
   config.build_settings['ENABLE_BITCODE'] = 'NO'
  end
 end
end

