target 'SampleApp' do
  platform :ios, '11.0'
  use_frameworks!

  pod 'ProtonCore-CoreTranslation', :path => "../../"
  pod 'ProtonCore-UIFoundations', :path => "../../"
  pod 'ProtonCore-Crypto', :path => "../../"
  pod 'ProtonCore-Keymaker', :path => "../../"
  pod 'ProtonCore-Log', :path => "../../"
  pod 'ProtonCore-Foundations', :path => "../../"

  pod 'ProtonCore-Settings', :path => "../../"

end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'No'
        end
    end
end
